spring.mvc.view.prefix=/WEB-INF/view/
spring.mvc.view.suffix=.jsp

db.driver=org.postgresql.Driver

db.url=jdbc:postgresql://localhost:5432/bookmanagement?useSSL=false
db.username=postgres
db.password=root

hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
hibernate.show_sql=true
hibernate.hbm2ddl.auto=create

entitymanager.packagesToScan=in.bushansirgur
server.port=8080